
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Application: 'Application',
  ApplicationQueue: 'ApplicationQueue'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ApplicationScalarFieldEnum = {
  id: 'id',
  postText: 'postText',
  authorName: 'authorName',
  authorTitle: 'authorTitle',
  postUrl: 'postUrl',
  datePosted: 'datePosted',
  likesCount: 'likesCount',
  source: 'source',
  externalUrls: 'externalUrls',
  linkedinJobUrls: 'linkedinJobUrls',
  linkedinProfileUrls: 'linkedinProfileUrls',
  hashtagsInText: 'hashtagsInText',
  scrapedAt: 'scrapedAt',
  activityUrn: 'activityUrn',
  postKind: 'postKind',
  jobRelevance: 'jobRelevance',
  isFit: 'isFit',
  fitScore: 'fitScore',
  fitReason: 'fitReason',
  roleDetected: 'roleDetected',
  companyDetected: 'companyDetected',
  locationDetected: 'locationDetected',
  employmentType: 'employmentType',
  seniority: 'seniority',
  salaryOrCompMentioned: 'salaryOrCompMentioned',
  requirements: 'requirements',
  requirementsNiceToHave: 'requirementsNiceToHave',
  skillsMatched: 'skillsMatched',
  skillsMissing: 'skillsMissing',
  redFlags: 'redFlags',
  nextStepForCandidate: 'nextStepForCandidate',
  action: 'action',
  isViewed: 'isViewed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ApplicationScalarFieldEnum = (typeof ApplicationScalarFieldEnum)[keyof typeof ApplicationScalarFieldEnum]


export const ApplicationQueueScalarFieldEnum = {
  id: 'id',
  payload: 'payload',
  postText: 'postText',
  scrapedAt: 'scrapedAt',
  source: 'source',
  postUrl: 'postUrl',
  status: 'status',
  attemptCount: 'attemptCount',
  workerId: 'workerId',
  lockedAt: 'lockedAt',
  processedAt: 'processedAt',
  appId: 'appId',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ApplicationQueueScalarFieldEnum = (typeof ApplicationQueueScalarFieldEnum)[keyof typeof ApplicationQueueScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

