
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApplicationQueue` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ApplicationQueue
 * 
 */
export type ApplicationQueueModel = runtime.Types.Result.DefaultSelection<Prisma.$ApplicationQueuePayload>

export type AggregateApplicationQueue = {
  _count: ApplicationQueueCountAggregateOutputType | null
  _avg: ApplicationQueueAvgAggregateOutputType | null
  _sum: ApplicationQueueSumAggregateOutputType | null
  _min: ApplicationQueueMinAggregateOutputType | null
  _max: ApplicationQueueMaxAggregateOutputType | null
}

export type ApplicationQueueAvgAggregateOutputType = {
  attemptCount: number | null
}

export type ApplicationQueueSumAggregateOutputType = {
  attemptCount: number | null
}

export type ApplicationQueueMinAggregateOutputType = {
  id: string | null
  postText: string | null
  scrapedAt: Date | null
  source: string | null
  postUrl: string | null
  status: string | null
  attemptCount: number | null
  workerId: string | null
  lockedAt: Date | null
  processedAt: Date | null
  appId: string | null
  errorMessage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ApplicationQueueMaxAggregateOutputType = {
  id: string | null
  postText: string | null
  scrapedAt: Date | null
  source: string | null
  postUrl: string | null
  status: string | null
  attemptCount: number | null
  workerId: string | null
  lockedAt: Date | null
  processedAt: Date | null
  appId: string | null
  errorMessage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ApplicationQueueCountAggregateOutputType = {
  id: number
  payload: number
  postText: number
  scrapedAt: number
  source: number
  postUrl: number
  status: number
  attemptCount: number
  workerId: number
  lockedAt: number
  processedAt: number
  appId: number
  errorMessage: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ApplicationQueueAvgAggregateInputType = {
  attemptCount?: true
}

export type ApplicationQueueSumAggregateInputType = {
  attemptCount?: true
}

export type ApplicationQueueMinAggregateInputType = {
  id?: true
  postText?: true
  scrapedAt?: true
  source?: true
  postUrl?: true
  status?: true
  attemptCount?: true
  workerId?: true
  lockedAt?: true
  processedAt?: true
  appId?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
}

export type ApplicationQueueMaxAggregateInputType = {
  id?: true
  postText?: true
  scrapedAt?: true
  source?: true
  postUrl?: true
  status?: true
  attemptCount?: true
  workerId?: true
  lockedAt?: true
  processedAt?: true
  appId?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
}

export type ApplicationQueueCountAggregateInputType = {
  id?: true
  payload?: true
  postText?: true
  scrapedAt?: true
  source?: true
  postUrl?: true
  status?: true
  attemptCount?: true
  workerId?: true
  lockedAt?: true
  processedAt?: true
  appId?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ApplicationQueueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApplicationQueue to aggregate.
   */
  where?: Prisma.ApplicationQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationQueues to fetch.
   */
  orderBy?: Prisma.ApplicationQueueOrderByWithRelationInput | Prisma.ApplicationQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApplicationQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApplicationQueues
  **/
  _count?: true | ApplicationQueueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApplicationQueueAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApplicationQueueSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApplicationQueueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApplicationQueueMaxAggregateInputType
}

export type GetApplicationQueueAggregateType<T extends ApplicationQueueAggregateArgs> = {
      [P in keyof T & keyof AggregateApplicationQueue]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApplicationQueue[P]>
    : Prisma.GetScalarType<T[P], AggregateApplicationQueue[P]>
}




export type ApplicationQueueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationQueueWhereInput
  orderBy?: Prisma.ApplicationQueueOrderByWithAggregationInput | Prisma.ApplicationQueueOrderByWithAggregationInput[]
  by: Prisma.ApplicationQueueScalarFieldEnum[] | Prisma.ApplicationQueueScalarFieldEnum
  having?: Prisma.ApplicationQueueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApplicationQueueCountAggregateInputType | true
  _avg?: ApplicationQueueAvgAggregateInputType
  _sum?: ApplicationQueueSumAggregateInputType
  _min?: ApplicationQueueMinAggregateInputType
  _max?: ApplicationQueueMaxAggregateInputType
}

export type ApplicationQueueGroupByOutputType = {
  id: string
  payload: runtime.JsonValue
  postText: string
  scrapedAt: Date
  source: string | null
  postUrl: string | null
  status: string
  attemptCount: number
  workerId: string | null
  lockedAt: Date | null
  processedAt: Date | null
  appId: string | null
  errorMessage: string | null
  createdAt: Date
  updatedAt: Date
  _count: ApplicationQueueCountAggregateOutputType | null
  _avg: ApplicationQueueAvgAggregateOutputType | null
  _sum: ApplicationQueueSumAggregateOutputType | null
  _min: ApplicationQueueMinAggregateOutputType | null
  _max: ApplicationQueueMaxAggregateOutputType | null
}

export type GetApplicationQueueGroupByPayload<T extends ApplicationQueueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApplicationQueueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApplicationQueueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApplicationQueueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApplicationQueueGroupByOutputType[P]>
      }
    >
  >



export type ApplicationQueueWhereInput = {
  AND?: Prisma.ApplicationQueueWhereInput | Prisma.ApplicationQueueWhereInput[]
  OR?: Prisma.ApplicationQueueWhereInput[]
  NOT?: Prisma.ApplicationQueueWhereInput | Prisma.ApplicationQueueWhereInput[]
  id?: Prisma.StringFilter<"ApplicationQueue"> | string
  payload?: Prisma.JsonFilter<"ApplicationQueue">
  postText?: Prisma.StringFilter<"ApplicationQueue"> | string
  scrapedAt?: Prisma.DateTimeFilter<"ApplicationQueue"> | Date | string
  source?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  postUrl?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  status?: Prisma.StringFilter<"ApplicationQueue"> | string
  attemptCount?: Prisma.IntFilter<"ApplicationQueue"> | number
  workerId?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  lockedAt?: Prisma.DateTimeNullableFilter<"ApplicationQueue"> | Date | string | null
  processedAt?: Prisma.DateTimeNullableFilter<"ApplicationQueue"> | Date | string | null
  appId?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  errorMessage?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ApplicationQueue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ApplicationQueue"> | Date | string
}

export type ApplicationQueueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  postUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  attemptCount?: Prisma.SortOrder
  workerId?: Prisma.SortOrderInput | Prisma.SortOrder
  lockedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  appId?: Prisma.SortOrderInput | Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApplicationQueueWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ApplicationQueueWhereInput | Prisma.ApplicationQueueWhereInput[]
  OR?: Prisma.ApplicationQueueWhereInput[]
  NOT?: Prisma.ApplicationQueueWhereInput | Prisma.ApplicationQueueWhereInput[]
  payload?: Prisma.JsonFilter<"ApplicationQueue">
  postText?: Prisma.StringFilter<"ApplicationQueue"> | string
  scrapedAt?: Prisma.DateTimeFilter<"ApplicationQueue"> | Date | string
  source?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  postUrl?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  status?: Prisma.StringFilter<"ApplicationQueue"> | string
  attemptCount?: Prisma.IntFilter<"ApplicationQueue"> | number
  workerId?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  lockedAt?: Prisma.DateTimeNullableFilter<"ApplicationQueue"> | Date | string | null
  processedAt?: Prisma.DateTimeNullableFilter<"ApplicationQueue"> | Date | string | null
  appId?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  errorMessage?: Prisma.StringNullableFilter<"ApplicationQueue"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ApplicationQueue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ApplicationQueue"> | Date | string
}, "id">

export type ApplicationQueueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  postUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  attemptCount?: Prisma.SortOrder
  workerId?: Prisma.SortOrderInput | Prisma.SortOrder
  lockedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  appId?: Prisma.SortOrderInput | Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ApplicationQueueCountOrderByAggregateInput
  _avg?: Prisma.ApplicationQueueAvgOrderByAggregateInput
  _max?: Prisma.ApplicationQueueMaxOrderByAggregateInput
  _min?: Prisma.ApplicationQueueMinOrderByAggregateInput
  _sum?: Prisma.ApplicationQueueSumOrderByAggregateInput
}

export type ApplicationQueueScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApplicationQueueScalarWhereWithAggregatesInput | Prisma.ApplicationQueueScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApplicationQueueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApplicationQueueScalarWhereWithAggregatesInput | Prisma.ApplicationQueueScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ApplicationQueue"> | string
  payload?: Prisma.JsonWithAggregatesFilter<"ApplicationQueue">
  postText?: Prisma.StringWithAggregatesFilter<"ApplicationQueue"> | string
  scrapedAt?: Prisma.DateTimeWithAggregatesFilter<"ApplicationQueue"> | Date | string
  source?: Prisma.StringNullableWithAggregatesFilter<"ApplicationQueue"> | string | null
  postUrl?: Prisma.StringNullableWithAggregatesFilter<"ApplicationQueue"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"ApplicationQueue"> | string
  attemptCount?: Prisma.IntWithAggregatesFilter<"ApplicationQueue"> | number
  workerId?: Prisma.StringNullableWithAggregatesFilter<"ApplicationQueue"> | string | null
  lockedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ApplicationQueue"> | Date | string | null
  processedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ApplicationQueue"> | Date | string | null
  appId?: Prisma.StringNullableWithAggregatesFilter<"ApplicationQueue"> | string | null
  errorMessage?: Prisma.StringNullableWithAggregatesFilter<"ApplicationQueue"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ApplicationQueue"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ApplicationQueue"> | Date | string
}

export type ApplicationQueueCreateInput = {
  id?: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  postText: string
  scrapedAt: Date | string
  source?: string | null
  postUrl?: string | null
  status?: string
  attemptCount?: number
  workerId?: string | null
  lockedAt?: Date | string | null
  processedAt?: Date | string | null
  appId?: string | null
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ApplicationQueueUncheckedCreateInput = {
  id?: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  postText: string
  scrapedAt: Date | string
  source?: string | null
  postUrl?: string | null
  status?: string
  attemptCount?: number
  workerId?: string | null
  lockedAt?: Date | string | null
  processedAt?: Date | string | null
  appId?: string | null
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ApplicationQueueUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  postText?: Prisma.StringFieldUpdateOperationsInput | string
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attemptCount?: Prisma.IntFieldUpdateOperationsInput | number
  workerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  appId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationQueueUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  postText?: Prisma.StringFieldUpdateOperationsInput | string
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attemptCount?: Prisma.IntFieldUpdateOperationsInput | number
  workerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  appId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationQueueCreateManyInput = {
  id?: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  postText: string
  scrapedAt: Date | string
  source?: string | null
  postUrl?: string | null
  status?: string
  attemptCount?: number
  workerId?: string | null
  lockedAt?: Date | string | null
  processedAt?: Date | string | null
  appId?: string | null
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ApplicationQueueUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  postText?: Prisma.StringFieldUpdateOperationsInput | string
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attemptCount?: Prisma.IntFieldUpdateOperationsInput | number
  workerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  appId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationQueueUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  postText?: Prisma.StringFieldUpdateOperationsInput | string
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attemptCount?: Prisma.IntFieldUpdateOperationsInput | number
  workerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lockedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  appId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationQueueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  source?: Prisma.SortOrder
  postUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attemptCount?: Prisma.SortOrder
  workerId?: Prisma.SortOrder
  lockedAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApplicationQueueAvgOrderByAggregateInput = {
  attemptCount?: Prisma.SortOrder
}

export type ApplicationQueueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  source?: Prisma.SortOrder
  postUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attemptCount?: Prisma.SortOrder
  workerId?: Prisma.SortOrder
  lockedAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApplicationQueueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  source?: Prisma.SortOrder
  postUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attemptCount?: Prisma.SortOrder
  workerId?: Prisma.SortOrder
  lockedAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApplicationQueueSumOrderByAggregateInput = {
  attemptCount?: Prisma.SortOrder
}



export type ApplicationQueueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payload?: boolean
  postText?: boolean
  scrapedAt?: boolean
  source?: boolean
  postUrl?: boolean
  status?: boolean
  attemptCount?: boolean
  workerId?: boolean
  lockedAt?: boolean
  processedAt?: boolean
  appId?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["applicationQueue"]>

export type ApplicationQueueSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payload?: boolean
  postText?: boolean
  scrapedAt?: boolean
  source?: boolean
  postUrl?: boolean
  status?: boolean
  attemptCount?: boolean
  workerId?: boolean
  lockedAt?: boolean
  processedAt?: boolean
  appId?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["applicationQueue"]>

export type ApplicationQueueSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payload?: boolean
  postText?: boolean
  scrapedAt?: boolean
  source?: boolean
  postUrl?: boolean
  status?: boolean
  attemptCount?: boolean
  workerId?: boolean
  lockedAt?: boolean
  processedAt?: boolean
  appId?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["applicationQueue"]>

export type ApplicationQueueSelectScalar = {
  id?: boolean
  payload?: boolean
  postText?: boolean
  scrapedAt?: boolean
  source?: boolean
  postUrl?: boolean
  status?: boolean
  attemptCount?: boolean
  workerId?: boolean
  lockedAt?: boolean
  processedAt?: boolean
  appId?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ApplicationQueueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "payload" | "postText" | "scrapedAt" | "source" | "postUrl" | "status" | "attemptCount" | "workerId" | "lockedAt" | "processedAt" | "appId" | "errorMessage" | "createdAt" | "updatedAt", ExtArgs["result"]["applicationQueue"]>

export type $ApplicationQueuePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApplicationQueue"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    payload: runtime.JsonValue
    postText: string
    scrapedAt: Date
    source: string | null
    postUrl: string | null
    status: string
    attemptCount: number
    workerId: string | null
    lockedAt: Date | null
    processedAt: Date | null
    appId: string | null
    errorMessage: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["applicationQueue"]>
  composites: {}
}

export type ApplicationQueueGetPayload<S extends boolean | null | undefined | ApplicationQueueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload, S>

export type ApplicationQueueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApplicationQueueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApplicationQueueCountAggregateInputType | true
  }

export interface ApplicationQueueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApplicationQueue'], meta: { name: 'ApplicationQueue' } }
  /**
   * Find zero or one ApplicationQueue that matches the filter.
   * @param {ApplicationQueueFindUniqueArgs} args - Arguments to find a ApplicationQueue
   * @example
   * // Get one ApplicationQueue
   * const applicationQueue = await prisma.applicationQueue.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApplicationQueueFindUniqueArgs>(args: Prisma.SelectSubset<T, ApplicationQueueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApplicationQueueClient<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApplicationQueue that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApplicationQueueFindUniqueOrThrowArgs} args - Arguments to find a ApplicationQueue
   * @example
   * // Get one ApplicationQueue
   * const applicationQueue = await prisma.applicationQueue.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApplicationQueueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApplicationQueueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationQueueClient<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApplicationQueue that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationQueueFindFirstArgs} args - Arguments to find a ApplicationQueue
   * @example
   * // Get one ApplicationQueue
   * const applicationQueue = await prisma.applicationQueue.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApplicationQueueFindFirstArgs>(args?: Prisma.SelectSubset<T, ApplicationQueueFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApplicationQueueClient<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApplicationQueue that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationQueueFindFirstOrThrowArgs} args - Arguments to find a ApplicationQueue
   * @example
   * // Get one ApplicationQueue
   * const applicationQueue = await prisma.applicationQueue.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApplicationQueueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApplicationQueueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationQueueClient<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApplicationQueues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationQueueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApplicationQueues
   * const applicationQueues = await prisma.applicationQueue.findMany()
   * 
   * // Get first 10 ApplicationQueues
   * const applicationQueues = await prisma.applicationQueue.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const applicationQueueWithIdOnly = await prisma.applicationQueue.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApplicationQueueFindManyArgs>(args?: Prisma.SelectSubset<T, ApplicationQueueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApplicationQueue.
   * @param {ApplicationQueueCreateArgs} args - Arguments to create a ApplicationQueue.
   * @example
   * // Create one ApplicationQueue
   * const ApplicationQueue = await prisma.applicationQueue.create({
   *   data: {
   *     // ... data to create a ApplicationQueue
   *   }
   * })
   * 
   */
  create<T extends ApplicationQueueCreateArgs>(args: Prisma.SelectSubset<T, ApplicationQueueCreateArgs<ExtArgs>>): Prisma.Prisma__ApplicationQueueClient<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApplicationQueues.
   * @param {ApplicationQueueCreateManyArgs} args - Arguments to create many ApplicationQueues.
   * @example
   * // Create many ApplicationQueues
   * const applicationQueue = await prisma.applicationQueue.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApplicationQueueCreateManyArgs>(args?: Prisma.SelectSubset<T, ApplicationQueueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApplicationQueues and returns the data saved in the database.
   * @param {ApplicationQueueCreateManyAndReturnArgs} args - Arguments to create many ApplicationQueues.
   * @example
   * // Create many ApplicationQueues
   * const applicationQueue = await prisma.applicationQueue.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApplicationQueues and only return the `id`
   * const applicationQueueWithIdOnly = await prisma.applicationQueue.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApplicationQueueCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApplicationQueueCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApplicationQueue.
   * @param {ApplicationQueueDeleteArgs} args - Arguments to delete one ApplicationQueue.
   * @example
   * // Delete one ApplicationQueue
   * const ApplicationQueue = await prisma.applicationQueue.delete({
   *   where: {
   *     // ... filter to delete one ApplicationQueue
   *   }
   * })
   * 
   */
  delete<T extends ApplicationQueueDeleteArgs>(args: Prisma.SelectSubset<T, ApplicationQueueDeleteArgs<ExtArgs>>): Prisma.Prisma__ApplicationQueueClient<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApplicationQueue.
   * @param {ApplicationQueueUpdateArgs} args - Arguments to update one ApplicationQueue.
   * @example
   * // Update one ApplicationQueue
   * const applicationQueue = await prisma.applicationQueue.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApplicationQueueUpdateArgs>(args: Prisma.SelectSubset<T, ApplicationQueueUpdateArgs<ExtArgs>>): Prisma.Prisma__ApplicationQueueClient<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApplicationQueues.
   * @param {ApplicationQueueDeleteManyArgs} args - Arguments to filter ApplicationQueues to delete.
   * @example
   * // Delete a few ApplicationQueues
   * const { count } = await prisma.applicationQueue.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApplicationQueueDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApplicationQueueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApplicationQueues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationQueueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApplicationQueues
   * const applicationQueue = await prisma.applicationQueue.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApplicationQueueUpdateManyArgs>(args: Prisma.SelectSubset<T, ApplicationQueueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApplicationQueues and returns the data updated in the database.
   * @param {ApplicationQueueUpdateManyAndReturnArgs} args - Arguments to update many ApplicationQueues.
   * @example
   * // Update many ApplicationQueues
   * const applicationQueue = await prisma.applicationQueue.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApplicationQueues and only return the `id`
   * const applicationQueueWithIdOnly = await prisma.applicationQueue.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApplicationQueueUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApplicationQueueUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApplicationQueue.
   * @param {ApplicationQueueUpsertArgs} args - Arguments to update or create a ApplicationQueue.
   * @example
   * // Update or create a ApplicationQueue
   * const applicationQueue = await prisma.applicationQueue.upsert({
   *   create: {
   *     // ... data to create a ApplicationQueue
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApplicationQueue we want to update
   *   }
   * })
   */
  upsert<T extends ApplicationQueueUpsertArgs>(args: Prisma.SelectSubset<T, ApplicationQueueUpsertArgs<ExtArgs>>): Prisma.Prisma__ApplicationQueueClient<runtime.Types.Result.GetResult<Prisma.$ApplicationQueuePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApplicationQueues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationQueueCountArgs} args - Arguments to filter ApplicationQueues to count.
   * @example
   * // Count the number of ApplicationQueues
   * const count = await prisma.applicationQueue.count({
   *   where: {
   *     // ... the filter for the ApplicationQueues we want to count
   *   }
   * })
  **/
  count<T extends ApplicationQueueCountArgs>(
    args?: Prisma.Subset<T, ApplicationQueueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApplicationQueueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApplicationQueue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationQueueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApplicationQueueAggregateArgs>(args: Prisma.Subset<T, ApplicationQueueAggregateArgs>): Prisma.PrismaPromise<GetApplicationQueueAggregateType<T>>

  /**
   * Group by ApplicationQueue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationQueueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApplicationQueueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApplicationQueueGroupByArgs['orderBy'] }
      : { orderBy?: ApplicationQueueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApplicationQueueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApplicationQueueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApplicationQueue model
 */
readonly fields: ApplicationQueueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApplicationQueue.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApplicationQueueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApplicationQueue model
 */
export interface ApplicationQueueFieldRefs {
  readonly id: Prisma.FieldRef<"ApplicationQueue", 'String'>
  readonly payload: Prisma.FieldRef<"ApplicationQueue", 'Json'>
  readonly postText: Prisma.FieldRef<"ApplicationQueue", 'String'>
  readonly scrapedAt: Prisma.FieldRef<"ApplicationQueue", 'DateTime'>
  readonly source: Prisma.FieldRef<"ApplicationQueue", 'String'>
  readonly postUrl: Prisma.FieldRef<"ApplicationQueue", 'String'>
  readonly status: Prisma.FieldRef<"ApplicationQueue", 'String'>
  readonly attemptCount: Prisma.FieldRef<"ApplicationQueue", 'Int'>
  readonly workerId: Prisma.FieldRef<"ApplicationQueue", 'String'>
  readonly lockedAt: Prisma.FieldRef<"ApplicationQueue", 'DateTime'>
  readonly processedAt: Prisma.FieldRef<"ApplicationQueue", 'DateTime'>
  readonly appId: Prisma.FieldRef<"ApplicationQueue", 'String'>
  readonly errorMessage: Prisma.FieldRef<"ApplicationQueue", 'String'>
  readonly createdAt: Prisma.FieldRef<"ApplicationQueue", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ApplicationQueue", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ApplicationQueue findUnique
 */
export type ApplicationQueueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * Filter, which ApplicationQueue to fetch.
   */
  where: Prisma.ApplicationQueueWhereUniqueInput
}

/**
 * ApplicationQueue findUniqueOrThrow
 */
export type ApplicationQueueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * Filter, which ApplicationQueue to fetch.
   */
  where: Prisma.ApplicationQueueWhereUniqueInput
}

/**
 * ApplicationQueue findFirst
 */
export type ApplicationQueueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * Filter, which ApplicationQueue to fetch.
   */
  where?: Prisma.ApplicationQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationQueues to fetch.
   */
  orderBy?: Prisma.ApplicationQueueOrderByWithRelationInput | Prisma.ApplicationQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApplicationQueues.
   */
  cursor?: Prisma.ApplicationQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationQueues.
   */
  distinct?: Prisma.ApplicationQueueScalarFieldEnum | Prisma.ApplicationQueueScalarFieldEnum[]
}

/**
 * ApplicationQueue findFirstOrThrow
 */
export type ApplicationQueueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * Filter, which ApplicationQueue to fetch.
   */
  where?: Prisma.ApplicationQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationQueues to fetch.
   */
  orderBy?: Prisma.ApplicationQueueOrderByWithRelationInput | Prisma.ApplicationQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApplicationQueues.
   */
  cursor?: Prisma.ApplicationQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationQueues.
   */
  distinct?: Prisma.ApplicationQueueScalarFieldEnum | Prisma.ApplicationQueueScalarFieldEnum[]
}

/**
 * ApplicationQueue findMany
 */
export type ApplicationQueueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * Filter, which ApplicationQueues to fetch.
   */
  where?: Prisma.ApplicationQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationQueues to fetch.
   */
  orderBy?: Prisma.ApplicationQueueOrderByWithRelationInput | Prisma.ApplicationQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApplicationQueues.
   */
  cursor?: Prisma.ApplicationQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationQueues.
   */
  distinct?: Prisma.ApplicationQueueScalarFieldEnum | Prisma.ApplicationQueueScalarFieldEnum[]
}

/**
 * ApplicationQueue create
 */
export type ApplicationQueueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * The data needed to create a ApplicationQueue.
   */
  data: Prisma.XOR<Prisma.ApplicationQueueCreateInput, Prisma.ApplicationQueueUncheckedCreateInput>
}

/**
 * ApplicationQueue createMany
 */
export type ApplicationQueueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApplicationQueues.
   */
  data: Prisma.ApplicationQueueCreateManyInput | Prisma.ApplicationQueueCreateManyInput[]
}

/**
 * ApplicationQueue createManyAndReturn
 */
export type ApplicationQueueCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * The data used to create many ApplicationQueues.
   */
  data: Prisma.ApplicationQueueCreateManyInput | Prisma.ApplicationQueueCreateManyInput[]
}

/**
 * ApplicationQueue update
 */
export type ApplicationQueueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * The data needed to update a ApplicationQueue.
   */
  data: Prisma.XOR<Prisma.ApplicationQueueUpdateInput, Prisma.ApplicationQueueUncheckedUpdateInput>
  /**
   * Choose, which ApplicationQueue to update.
   */
  where: Prisma.ApplicationQueueWhereUniqueInput
}

/**
 * ApplicationQueue updateMany
 */
export type ApplicationQueueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApplicationQueues.
   */
  data: Prisma.XOR<Prisma.ApplicationQueueUpdateManyMutationInput, Prisma.ApplicationQueueUncheckedUpdateManyInput>
  /**
   * Filter which ApplicationQueues to update
   */
  where?: Prisma.ApplicationQueueWhereInput
  /**
   * Limit how many ApplicationQueues to update.
   */
  limit?: number
}

/**
 * ApplicationQueue updateManyAndReturn
 */
export type ApplicationQueueUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * The data used to update ApplicationQueues.
   */
  data: Prisma.XOR<Prisma.ApplicationQueueUpdateManyMutationInput, Prisma.ApplicationQueueUncheckedUpdateManyInput>
  /**
   * Filter which ApplicationQueues to update
   */
  where?: Prisma.ApplicationQueueWhereInput
  /**
   * Limit how many ApplicationQueues to update.
   */
  limit?: number
}

/**
 * ApplicationQueue upsert
 */
export type ApplicationQueueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * The filter to search for the ApplicationQueue to update in case it exists.
   */
  where: Prisma.ApplicationQueueWhereUniqueInput
  /**
   * In case the ApplicationQueue found by the `where` argument doesn't exist, create a new ApplicationQueue with this data.
   */
  create: Prisma.XOR<Prisma.ApplicationQueueCreateInput, Prisma.ApplicationQueueUncheckedCreateInput>
  /**
   * In case the ApplicationQueue was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApplicationQueueUpdateInput, Prisma.ApplicationQueueUncheckedUpdateInput>
}

/**
 * ApplicationQueue delete
 */
export type ApplicationQueueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
  /**
   * Filter which ApplicationQueue to delete.
   */
  where: Prisma.ApplicationQueueWhereUniqueInput
}

/**
 * ApplicationQueue deleteMany
 */
export type ApplicationQueueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApplicationQueues to delete
   */
  where?: Prisma.ApplicationQueueWhereInput
  /**
   * Limit how many ApplicationQueues to delete.
   */
  limit?: number
}

/**
 * ApplicationQueue without action
 */
export type ApplicationQueueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationQueue
   */
  select?: Prisma.ApplicationQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationQueue
   */
  omit?: Prisma.ApplicationQueueOmit<ExtArgs> | null
}
