
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Application` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Application
 * 
 */
export type ApplicationModel = runtime.Types.Result.DefaultSelection<Prisma.$ApplicationPayload>

export type AggregateApplication = {
  _count: ApplicationCountAggregateOutputType | null
  _avg: ApplicationAvgAggregateOutputType | null
  _sum: ApplicationSumAggregateOutputType | null
  _min: ApplicationMinAggregateOutputType | null
  _max: ApplicationMaxAggregateOutputType | null
}

export type ApplicationAvgAggregateOutputType = {
  likesCount: number | null
  jobRelevance: number | null
  fitScore: number | null
}

export type ApplicationSumAggregateOutputType = {
  likesCount: number | null
  jobRelevance: number | null
  fitScore: number | null
}

export type ApplicationMinAggregateOutputType = {
  id: string | null
  postText: string | null
  authorName: string | null
  authorTitle: string | null
  postUrl: string | null
  datePosted: Date | null
  likesCount: number | null
  source: string | null
  externalUrls: string | null
  linkedinJobUrls: string | null
  linkedinProfileUrls: string | null
  hashtagsInText: string | null
  scrapedAt: Date | null
  activityUrn: string | null
  postKind: string | null
  jobRelevance: number | null
  isFit: boolean | null
  fitScore: number | null
  fitReason: string | null
  roleDetected: string | null
  companyDetected: string | null
  locationDetected: string | null
  employmentType: string | null
  seniority: string | null
  salaryOrCompMentioned: string | null
  requirements: string | null
  requirementsNiceToHave: string | null
  skillsMatched: string | null
  skillsMissing: string | null
  redFlags: string | null
  nextStepForCandidate: string | null
  action: string | null
  isViewed: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ApplicationMaxAggregateOutputType = {
  id: string | null
  postText: string | null
  authorName: string | null
  authorTitle: string | null
  postUrl: string | null
  datePosted: Date | null
  likesCount: number | null
  source: string | null
  externalUrls: string | null
  linkedinJobUrls: string | null
  linkedinProfileUrls: string | null
  hashtagsInText: string | null
  scrapedAt: Date | null
  activityUrn: string | null
  postKind: string | null
  jobRelevance: number | null
  isFit: boolean | null
  fitScore: number | null
  fitReason: string | null
  roleDetected: string | null
  companyDetected: string | null
  locationDetected: string | null
  employmentType: string | null
  seniority: string | null
  salaryOrCompMentioned: string | null
  requirements: string | null
  requirementsNiceToHave: string | null
  skillsMatched: string | null
  skillsMissing: string | null
  redFlags: string | null
  nextStepForCandidate: string | null
  action: string | null
  isViewed: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ApplicationCountAggregateOutputType = {
  id: number
  postText: number
  authorName: number
  authorTitle: number
  postUrl: number
  datePosted: number
  likesCount: number
  source: number
  externalUrls: number
  linkedinJobUrls: number
  linkedinProfileUrls: number
  hashtagsInText: number
  scrapedAt: number
  activityUrn: number
  postKind: number
  jobRelevance: number
  isFit: number
  fitScore: number
  fitReason: number
  roleDetected: number
  companyDetected: number
  locationDetected: number
  employmentType: number
  seniority: number
  salaryOrCompMentioned: number
  requirements: number
  requirementsNiceToHave: number
  skillsMatched: number
  skillsMissing: number
  redFlags: number
  nextStepForCandidate: number
  action: number
  isViewed: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ApplicationAvgAggregateInputType = {
  likesCount?: true
  jobRelevance?: true
  fitScore?: true
}

export type ApplicationSumAggregateInputType = {
  likesCount?: true
  jobRelevance?: true
  fitScore?: true
}

export type ApplicationMinAggregateInputType = {
  id?: true
  postText?: true
  authorName?: true
  authorTitle?: true
  postUrl?: true
  datePosted?: true
  likesCount?: true
  source?: true
  externalUrls?: true
  linkedinJobUrls?: true
  linkedinProfileUrls?: true
  hashtagsInText?: true
  scrapedAt?: true
  activityUrn?: true
  postKind?: true
  jobRelevance?: true
  isFit?: true
  fitScore?: true
  fitReason?: true
  roleDetected?: true
  companyDetected?: true
  locationDetected?: true
  employmentType?: true
  seniority?: true
  salaryOrCompMentioned?: true
  requirements?: true
  requirementsNiceToHave?: true
  skillsMatched?: true
  skillsMissing?: true
  redFlags?: true
  nextStepForCandidate?: true
  action?: true
  isViewed?: true
  createdAt?: true
  updatedAt?: true
}

export type ApplicationMaxAggregateInputType = {
  id?: true
  postText?: true
  authorName?: true
  authorTitle?: true
  postUrl?: true
  datePosted?: true
  likesCount?: true
  source?: true
  externalUrls?: true
  linkedinJobUrls?: true
  linkedinProfileUrls?: true
  hashtagsInText?: true
  scrapedAt?: true
  activityUrn?: true
  postKind?: true
  jobRelevance?: true
  isFit?: true
  fitScore?: true
  fitReason?: true
  roleDetected?: true
  companyDetected?: true
  locationDetected?: true
  employmentType?: true
  seniority?: true
  salaryOrCompMentioned?: true
  requirements?: true
  requirementsNiceToHave?: true
  skillsMatched?: true
  skillsMissing?: true
  redFlags?: true
  nextStepForCandidate?: true
  action?: true
  isViewed?: true
  createdAt?: true
  updatedAt?: true
}

export type ApplicationCountAggregateInputType = {
  id?: true
  postText?: true
  authorName?: true
  authorTitle?: true
  postUrl?: true
  datePosted?: true
  likesCount?: true
  source?: true
  externalUrls?: true
  linkedinJobUrls?: true
  linkedinProfileUrls?: true
  hashtagsInText?: true
  scrapedAt?: true
  activityUrn?: true
  postKind?: true
  jobRelevance?: true
  isFit?: true
  fitScore?: true
  fitReason?: true
  roleDetected?: true
  companyDetected?: true
  locationDetected?: true
  employmentType?: true
  seniority?: true
  salaryOrCompMentioned?: true
  requirements?: true
  requirementsNiceToHave?: true
  skillsMatched?: true
  skillsMissing?: true
  redFlags?: true
  nextStepForCandidate?: true
  action?: true
  isViewed?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ApplicationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Application to aggregate.
   */
  where?: Prisma.ApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Applications to fetch.
   */
  orderBy?: Prisma.ApplicationOrderByWithRelationInput | Prisma.ApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Applications
  **/
  _count?: true | ApplicationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApplicationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApplicationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApplicationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApplicationMaxAggregateInputType
}

export type GetApplicationAggregateType<T extends ApplicationAggregateArgs> = {
      [P in keyof T & keyof AggregateApplication]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApplication[P]>
    : Prisma.GetScalarType<T[P], AggregateApplication[P]>
}




export type ApplicationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationWhereInput
  orderBy?: Prisma.ApplicationOrderByWithAggregationInput | Prisma.ApplicationOrderByWithAggregationInput[]
  by: Prisma.ApplicationScalarFieldEnum[] | Prisma.ApplicationScalarFieldEnum
  having?: Prisma.ApplicationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApplicationCountAggregateInputType | true
  _avg?: ApplicationAvgAggregateInputType
  _sum?: ApplicationSumAggregateInputType
  _min?: ApplicationMinAggregateInputType
  _max?: ApplicationMaxAggregateInputType
}

export type ApplicationGroupByOutputType = {
  id: string
  postText: string
  authorName: string | null
  authorTitle: string | null
  postUrl: string | null
  datePosted: Date | null
  likesCount: number
  source: string | null
  externalUrls: string | null
  linkedinJobUrls: string | null
  linkedinProfileUrls: string | null
  hashtagsInText: string | null
  scrapedAt: Date
  activityUrn: string | null
  postKind: string | null
  jobRelevance: number | null
  isFit: boolean
  fitScore: number | null
  fitReason: string | null
  roleDetected: string | null
  companyDetected: string | null
  locationDetected: string | null
  employmentType: string | null
  seniority: string | null
  salaryOrCompMentioned: string | null
  requirements: string | null
  requirementsNiceToHave: string | null
  skillsMatched: string | null
  skillsMissing: string | null
  redFlags: string | null
  nextStepForCandidate: string | null
  action: string | null
  isViewed: boolean
  createdAt: Date
  updatedAt: Date
  _count: ApplicationCountAggregateOutputType | null
  _avg: ApplicationAvgAggregateOutputType | null
  _sum: ApplicationSumAggregateOutputType | null
  _min: ApplicationMinAggregateOutputType | null
  _max: ApplicationMaxAggregateOutputType | null
}

export type GetApplicationGroupByPayload<T extends ApplicationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApplicationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApplicationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApplicationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApplicationGroupByOutputType[P]>
      }
    >
  >



export type ApplicationWhereInput = {
  AND?: Prisma.ApplicationWhereInput | Prisma.ApplicationWhereInput[]
  OR?: Prisma.ApplicationWhereInput[]
  NOT?: Prisma.ApplicationWhereInput | Prisma.ApplicationWhereInput[]
  id?: Prisma.StringFilter<"Application"> | string
  postText?: Prisma.StringFilter<"Application"> | string
  authorName?: Prisma.StringNullableFilter<"Application"> | string | null
  authorTitle?: Prisma.StringNullableFilter<"Application"> | string | null
  postUrl?: Prisma.StringNullableFilter<"Application"> | string | null
  datePosted?: Prisma.DateTimeNullableFilter<"Application"> | Date | string | null
  likesCount?: Prisma.IntFilter<"Application"> | number
  source?: Prisma.StringNullableFilter<"Application"> | string | null
  externalUrls?: Prisma.StringNullableFilter<"Application"> | string | null
  linkedinJobUrls?: Prisma.StringNullableFilter<"Application"> | string | null
  linkedinProfileUrls?: Prisma.StringNullableFilter<"Application"> | string | null
  hashtagsInText?: Prisma.StringNullableFilter<"Application"> | string | null
  scrapedAt?: Prisma.DateTimeFilter<"Application"> | Date | string
  activityUrn?: Prisma.StringNullableFilter<"Application"> | string | null
  postKind?: Prisma.StringNullableFilter<"Application"> | string | null
  jobRelevance?: Prisma.IntNullableFilter<"Application"> | number | null
  isFit?: Prisma.BoolFilter<"Application"> | boolean
  fitScore?: Prisma.IntNullableFilter<"Application"> | number | null
  fitReason?: Prisma.StringNullableFilter<"Application"> | string | null
  roleDetected?: Prisma.StringNullableFilter<"Application"> | string | null
  companyDetected?: Prisma.StringNullableFilter<"Application"> | string | null
  locationDetected?: Prisma.StringNullableFilter<"Application"> | string | null
  employmentType?: Prisma.StringNullableFilter<"Application"> | string | null
  seniority?: Prisma.StringNullableFilter<"Application"> | string | null
  salaryOrCompMentioned?: Prisma.StringNullableFilter<"Application"> | string | null
  requirements?: Prisma.StringNullableFilter<"Application"> | string | null
  requirementsNiceToHave?: Prisma.StringNullableFilter<"Application"> | string | null
  skillsMatched?: Prisma.StringNullableFilter<"Application"> | string | null
  skillsMissing?: Prisma.StringNullableFilter<"Application"> | string | null
  redFlags?: Prisma.StringNullableFilter<"Application"> | string | null
  nextStepForCandidate?: Prisma.StringNullableFilter<"Application"> | string | null
  action?: Prisma.StringNullableFilter<"Application"> | string | null
  isViewed?: Prisma.BoolFilter<"Application"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Application"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Application"> | Date | string
}

export type ApplicationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  authorName?: Prisma.SortOrderInput | Prisma.SortOrder
  authorTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  postUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  datePosted?: Prisma.SortOrderInput | Prisma.SortOrder
  likesCount?: Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  externalUrls?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedinJobUrls?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedinProfileUrls?: Prisma.SortOrderInput | Prisma.SortOrder
  hashtagsInText?: Prisma.SortOrderInput | Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  activityUrn?: Prisma.SortOrderInput | Prisma.SortOrder
  postKind?: Prisma.SortOrderInput | Prisma.SortOrder
  jobRelevance?: Prisma.SortOrderInput | Prisma.SortOrder
  isFit?: Prisma.SortOrder
  fitScore?: Prisma.SortOrderInput | Prisma.SortOrder
  fitReason?: Prisma.SortOrderInput | Prisma.SortOrder
  roleDetected?: Prisma.SortOrderInput | Prisma.SortOrder
  companyDetected?: Prisma.SortOrderInput | Prisma.SortOrder
  locationDetected?: Prisma.SortOrderInput | Prisma.SortOrder
  employmentType?: Prisma.SortOrderInput | Prisma.SortOrder
  seniority?: Prisma.SortOrderInput | Prisma.SortOrder
  salaryOrCompMentioned?: Prisma.SortOrderInput | Prisma.SortOrder
  requirements?: Prisma.SortOrderInput | Prisma.SortOrder
  requirementsNiceToHave?: Prisma.SortOrderInput | Prisma.SortOrder
  skillsMatched?: Prisma.SortOrderInput | Prisma.SortOrder
  skillsMissing?: Prisma.SortOrderInput | Prisma.SortOrder
  redFlags?: Prisma.SortOrderInput | Prisma.SortOrder
  nextStepForCandidate?: Prisma.SortOrderInput | Prisma.SortOrder
  action?: Prisma.SortOrderInput | Prisma.SortOrder
  isViewed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApplicationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ApplicationWhereInput | Prisma.ApplicationWhereInput[]
  OR?: Prisma.ApplicationWhereInput[]
  NOT?: Prisma.ApplicationWhereInput | Prisma.ApplicationWhereInput[]
  postText?: Prisma.StringFilter<"Application"> | string
  authorName?: Prisma.StringNullableFilter<"Application"> | string | null
  authorTitle?: Prisma.StringNullableFilter<"Application"> | string | null
  postUrl?: Prisma.StringNullableFilter<"Application"> | string | null
  datePosted?: Prisma.DateTimeNullableFilter<"Application"> | Date | string | null
  likesCount?: Prisma.IntFilter<"Application"> | number
  source?: Prisma.StringNullableFilter<"Application"> | string | null
  externalUrls?: Prisma.StringNullableFilter<"Application"> | string | null
  linkedinJobUrls?: Prisma.StringNullableFilter<"Application"> | string | null
  linkedinProfileUrls?: Prisma.StringNullableFilter<"Application"> | string | null
  hashtagsInText?: Prisma.StringNullableFilter<"Application"> | string | null
  scrapedAt?: Prisma.DateTimeFilter<"Application"> | Date | string
  activityUrn?: Prisma.StringNullableFilter<"Application"> | string | null
  postKind?: Prisma.StringNullableFilter<"Application"> | string | null
  jobRelevance?: Prisma.IntNullableFilter<"Application"> | number | null
  isFit?: Prisma.BoolFilter<"Application"> | boolean
  fitScore?: Prisma.IntNullableFilter<"Application"> | number | null
  fitReason?: Prisma.StringNullableFilter<"Application"> | string | null
  roleDetected?: Prisma.StringNullableFilter<"Application"> | string | null
  companyDetected?: Prisma.StringNullableFilter<"Application"> | string | null
  locationDetected?: Prisma.StringNullableFilter<"Application"> | string | null
  employmentType?: Prisma.StringNullableFilter<"Application"> | string | null
  seniority?: Prisma.StringNullableFilter<"Application"> | string | null
  salaryOrCompMentioned?: Prisma.StringNullableFilter<"Application"> | string | null
  requirements?: Prisma.StringNullableFilter<"Application"> | string | null
  requirementsNiceToHave?: Prisma.StringNullableFilter<"Application"> | string | null
  skillsMatched?: Prisma.StringNullableFilter<"Application"> | string | null
  skillsMissing?: Prisma.StringNullableFilter<"Application"> | string | null
  redFlags?: Prisma.StringNullableFilter<"Application"> | string | null
  nextStepForCandidate?: Prisma.StringNullableFilter<"Application"> | string | null
  action?: Prisma.StringNullableFilter<"Application"> | string | null
  isViewed?: Prisma.BoolFilter<"Application"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Application"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Application"> | Date | string
}, "id">

export type ApplicationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  authorName?: Prisma.SortOrderInput | Prisma.SortOrder
  authorTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  postUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  datePosted?: Prisma.SortOrderInput | Prisma.SortOrder
  likesCount?: Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  externalUrls?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedinJobUrls?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedinProfileUrls?: Prisma.SortOrderInput | Prisma.SortOrder
  hashtagsInText?: Prisma.SortOrderInput | Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  activityUrn?: Prisma.SortOrderInput | Prisma.SortOrder
  postKind?: Prisma.SortOrderInput | Prisma.SortOrder
  jobRelevance?: Prisma.SortOrderInput | Prisma.SortOrder
  isFit?: Prisma.SortOrder
  fitScore?: Prisma.SortOrderInput | Prisma.SortOrder
  fitReason?: Prisma.SortOrderInput | Prisma.SortOrder
  roleDetected?: Prisma.SortOrderInput | Prisma.SortOrder
  companyDetected?: Prisma.SortOrderInput | Prisma.SortOrder
  locationDetected?: Prisma.SortOrderInput | Prisma.SortOrder
  employmentType?: Prisma.SortOrderInput | Prisma.SortOrder
  seniority?: Prisma.SortOrderInput | Prisma.SortOrder
  salaryOrCompMentioned?: Prisma.SortOrderInput | Prisma.SortOrder
  requirements?: Prisma.SortOrderInput | Prisma.SortOrder
  requirementsNiceToHave?: Prisma.SortOrderInput | Prisma.SortOrder
  skillsMatched?: Prisma.SortOrderInput | Prisma.SortOrder
  skillsMissing?: Prisma.SortOrderInput | Prisma.SortOrder
  redFlags?: Prisma.SortOrderInput | Prisma.SortOrder
  nextStepForCandidate?: Prisma.SortOrderInput | Prisma.SortOrder
  action?: Prisma.SortOrderInput | Prisma.SortOrder
  isViewed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ApplicationCountOrderByAggregateInput
  _avg?: Prisma.ApplicationAvgOrderByAggregateInput
  _max?: Prisma.ApplicationMaxOrderByAggregateInput
  _min?: Prisma.ApplicationMinOrderByAggregateInput
  _sum?: Prisma.ApplicationSumOrderByAggregateInput
}

export type ApplicationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApplicationScalarWhereWithAggregatesInput | Prisma.ApplicationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApplicationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApplicationScalarWhereWithAggregatesInput | Prisma.ApplicationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Application"> | string
  postText?: Prisma.StringWithAggregatesFilter<"Application"> | string
  authorName?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  authorTitle?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  postUrl?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  datePosted?: Prisma.DateTimeNullableWithAggregatesFilter<"Application"> | Date | string | null
  likesCount?: Prisma.IntWithAggregatesFilter<"Application"> | number
  source?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  externalUrls?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  linkedinJobUrls?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  linkedinProfileUrls?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  hashtagsInText?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  scrapedAt?: Prisma.DateTimeWithAggregatesFilter<"Application"> | Date | string
  activityUrn?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  postKind?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  jobRelevance?: Prisma.IntNullableWithAggregatesFilter<"Application"> | number | null
  isFit?: Prisma.BoolWithAggregatesFilter<"Application"> | boolean
  fitScore?: Prisma.IntNullableWithAggregatesFilter<"Application"> | number | null
  fitReason?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  roleDetected?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  companyDetected?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  locationDetected?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  employmentType?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  seniority?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  salaryOrCompMentioned?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  requirements?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  requirementsNiceToHave?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  skillsMatched?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  skillsMissing?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  redFlags?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  nextStepForCandidate?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  action?: Prisma.StringNullableWithAggregatesFilter<"Application"> | string | null
  isViewed?: Prisma.BoolWithAggregatesFilter<"Application"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Application"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Application"> | Date | string
}

export type ApplicationCreateInput = {
  id?: string
  postText: string
  authorName?: string | null
  authorTitle?: string | null
  postUrl?: string | null
  datePosted?: Date | string | null
  likesCount?: number
  source?: string | null
  externalUrls?: string | null
  linkedinJobUrls?: string | null
  linkedinProfileUrls?: string | null
  hashtagsInText?: string | null
  scrapedAt: Date | string
  activityUrn?: string | null
  postKind?: string | null
  jobRelevance?: number | null
  isFit?: boolean
  fitScore?: number | null
  fitReason?: string | null
  roleDetected?: string | null
  companyDetected?: string | null
  locationDetected?: string | null
  employmentType?: string | null
  seniority?: string | null
  salaryOrCompMentioned?: string | null
  requirements?: string | null
  requirementsNiceToHave?: string | null
  skillsMatched?: string | null
  skillsMissing?: string | null
  redFlags?: string | null
  nextStepForCandidate?: string | null
  action?: string | null
  isViewed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ApplicationUncheckedCreateInput = {
  id?: string
  postText: string
  authorName?: string | null
  authorTitle?: string | null
  postUrl?: string | null
  datePosted?: Date | string | null
  likesCount?: number
  source?: string | null
  externalUrls?: string | null
  linkedinJobUrls?: string | null
  linkedinProfileUrls?: string | null
  hashtagsInText?: string | null
  scrapedAt: Date | string
  activityUrn?: string | null
  postKind?: string | null
  jobRelevance?: number | null
  isFit?: boolean
  fitScore?: number | null
  fitReason?: string | null
  roleDetected?: string | null
  companyDetected?: string | null
  locationDetected?: string | null
  employmentType?: string | null
  seniority?: string | null
  salaryOrCompMentioned?: string | null
  requirements?: string | null
  requirementsNiceToHave?: string | null
  skillsMatched?: string | null
  skillsMissing?: string | null
  redFlags?: string | null
  nextStepForCandidate?: string | null
  action?: string | null
  isViewed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ApplicationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postText?: Prisma.StringFieldUpdateOperationsInput | string
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePosted?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  likesCount?: Prisma.IntFieldUpdateOperationsInput | number
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinJobUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinProfileUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hashtagsInText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  activityUrn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postKind?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobRelevance?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isFit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fitScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fitReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employmentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seniority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  salaryOrCompMentioned?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requirements?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requirementsNiceToHave?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skillsMatched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skillsMissing?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redFlags?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextStepForCandidate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isViewed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postText?: Prisma.StringFieldUpdateOperationsInput | string
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePosted?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  likesCount?: Prisma.IntFieldUpdateOperationsInput | number
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinJobUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinProfileUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hashtagsInText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  activityUrn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postKind?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobRelevance?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isFit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fitScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fitReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employmentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seniority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  salaryOrCompMentioned?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requirements?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requirementsNiceToHave?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skillsMatched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skillsMissing?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redFlags?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextStepForCandidate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isViewed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationCreateManyInput = {
  id?: string
  postText: string
  authorName?: string | null
  authorTitle?: string | null
  postUrl?: string | null
  datePosted?: Date | string | null
  likesCount?: number
  source?: string | null
  externalUrls?: string | null
  linkedinJobUrls?: string | null
  linkedinProfileUrls?: string | null
  hashtagsInText?: string | null
  scrapedAt: Date | string
  activityUrn?: string | null
  postKind?: string | null
  jobRelevance?: number | null
  isFit?: boolean
  fitScore?: number | null
  fitReason?: string | null
  roleDetected?: string | null
  companyDetected?: string | null
  locationDetected?: string | null
  employmentType?: string | null
  seniority?: string | null
  salaryOrCompMentioned?: string | null
  requirements?: string | null
  requirementsNiceToHave?: string | null
  skillsMatched?: string | null
  skillsMissing?: string | null
  redFlags?: string | null
  nextStepForCandidate?: string | null
  action?: string | null
  isViewed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ApplicationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postText?: Prisma.StringFieldUpdateOperationsInput | string
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePosted?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  likesCount?: Prisma.IntFieldUpdateOperationsInput | number
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinJobUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinProfileUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hashtagsInText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  activityUrn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postKind?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobRelevance?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isFit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fitScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fitReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employmentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seniority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  salaryOrCompMentioned?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requirements?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requirementsNiceToHave?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skillsMatched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skillsMissing?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redFlags?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextStepForCandidate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isViewed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postText?: Prisma.StringFieldUpdateOperationsInput | string
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePosted?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  likesCount?: Prisma.IntFieldUpdateOperationsInput | number
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinJobUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinProfileUrls?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hashtagsInText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  activityUrn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postKind?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobRelevance?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isFit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  fitScore?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fitReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locationDetected?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  employmentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seniority?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  salaryOrCompMentioned?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requirements?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requirementsNiceToHave?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skillsMatched?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skillsMissing?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redFlags?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nextStepForCandidate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isViewed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorTitle?: Prisma.SortOrder
  postUrl?: Prisma.SortOrder
  datePosted?: Prisma.SortOrder
  likesCount?: Prisma.SortOrder
  source?: Prisma.SortOrder
  externalUrls?: Prisma.SortOrder
  linkedinJobUrls?: Prisma.SortOrder
  linkedinProfileUrls?: Prisma.SortOrder
  hashtagsInText?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  activityUrn?: Prisma.SortOrder
  postKind?: Prisma.SortOrder
  jobRelevance?: Prisma.SortOrder
  isFit?: Prisma.SortOrder
  fitScore?: Prisma.SortOrder
  fitReason?: Prisma.SortOrder
  roleDetected?: Prisma.SortOrder
  companyDetected?: Prisma.SortOrder
  locationDetected?: Prisma.SortOrder
  employmentType?: Prisma.SortOrder
  seniority?: Prisma.SortOrder
  salaryOrCompMentioned?: Prisma.SortOrder
  requirements?: Prisma.SortOrder
  requirementsNiceToHave?: Prisma.SortOrder
  skillsMatched?: Prisma.SortOrder
  skillsMissing?: Prisma.SortOrder
  redFlags?: Prisma.SortOrder
  nextStepForCandidate?: Prisma.SortOrder
  action?: Prisma.SortOrder
  isViewed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApplicationAvgOrderByAggregateInput = {
  likesCount?: Prisma.SortOrder
  jobRelevance?: Prisma.SortOrder
  fitScore?: Prisma.SortOrder
}

export type ApplicationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorTitle?: Prisma.SortOrder
  postUrl?: Prisma.SortOrder
  datePosted?: Prisma.SortOrder
  likesCount?: Prisma.SortOrder
  source?: Prisma.SortOrder
  externalUrls?: Prisma.SortOrder
  linkedinJobUrls?: Prisma.SortOrder
  linkedinProfileUrls?: Prisma.SortOrder
  hashtagsInText?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  activityUrn?: Prisma.SortOrder
  postKind?: Prisma.SortOrder
  jobRelevance?: Prisma.SortOrder
  isFit?: Prisma.SortOrder
  fitScore?: Prisma.SortOrder
  fitReason?: Prisma.SortOrder
  roleDetected?: Prisma.SortOrder
  companyDetected?: Prisma.SortOrder
  locationDetected?: Prisma.SortOrder
  employmentType?: Prisma.SortOrder
  seniority?: Prisma.SortOrder
  salaryOrCompMentioned?: Prisma.SortOrder
  requirements?: Prisma.SortOrder
  requirementsNiceToHave?: Prisma.SortOrder
  skillsMatched?: Prisma.SortOrder
  skillsMissing?: Prisma.SortOrder
  redFlags?: Prisma.SortOrder
  nextStepForCandidate?: Prisma.SortOrder
  action?: Prisma.SortOrder
  isViewed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApplicationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postText?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorTitle?: Prisma.SortOrder
  postUrl?: Prisma.SortOrder
  datePosted?: Prisma.SortOrder
  likesCount?: Prisma.SortOrder
  source?: Prisma.SortOrder
  externalUrls?: Prisma.SortOrder
  linkedinJobUrls?: Prisma.SortOrder
  linkedinProfileUrls?: Prisma.SortOrder
  hashtagsInText?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  activityUrn?: Prisma.SortOrder
  postKind?: Prisma.SortOrder
  jobRelevance?: Prisma.SortOrder
  isFit?: Prisma.SortOrder
  fitScore?: Prisma.SortOrder
  fitReason?: Prisma.SortOrder
  roleDetected?: Prisma.SortOrder
  companyDetected?: Prisma.SortOrder
  locationDetected?: Prisma.SortOrder
  employmentType?: Prisma.SortOrder
  seniority?: Prisma.SortOrder
  salaryOrCompMentioned?: Prisma.SortOrder
  requirements?: Prisma.SortOrder
  requirementsNiceToHave?: Prisma.SortOrder
  skillsMatched?: Prisma.SortOrder
  skillsMissing?: Prisma.SortOrder
  redFlags?: Prisma.SortOrder
  nextStepForCandidate?: Prisma.SortOrder
  action?: Prisma.SortOrder
  isViewed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApplicationSumOrderByAggregateInput = {
  likesCount?: Prisma.SortOrder
  jobRelevance?: Prisma.SortOrder
  fitScore?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type ApplicationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  postText?: boolean
  authorName?: boolean
  authorTitle?: boolean
  postUrl?: boolean
  datePosted?: boolean
  likesCount?: boolean
  source?: boolean
  externalUrls?: boolean
  linkedinJobUrls?: boolean
  linkedinProfileUrls?: boolean
  hashtagsInText?: boolean
  scrapedAt?: boolean
  activityUrn?: boolean
  postKind?: boolean
  jobRelevance?: boolean
  isFit?: boolean
  fitScore?: boolean
  fitReason?: boolean
  roleDetected?: boolean
  companyDetected?: boolean
  locationDetected?: boolean
  employmentType?: boolean
  seniority?: boolean
  salaryOrCompMentioned?: boolean
  requirements?: boolean
  requirementsNiceToHave?: boolean
  skillsMatched?: boolean
  skillsMissing?: boolean
  redFlags?: boolean
  nextStepForCandidate?: boolean
  action?: boolean
  isViewed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["application"]>

export type ApplicationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  postText?: boolean
  authorName?: boolean
  authorTitle?: boolean
  postUrl?: boolean
  datePosted?: boolean
  likesCount?: boolean
  source?: boolean
  externalUrls?: boolean
  linkedinJobUrls?: boolean
  linkedinProfileUrls?: boolean
  hashtagsInText?: boolean
  scrapedAt?: boolean
  activityUrn?: boolean
  postKind?: boolean
  jobRelevance?: boolean
  isFit?: boolean
  fitScore?: boolean
  fitReason?: boolean
  roleDetected?: boolean
  companyDetected?: boolean
  locationDetected?: boolean
  employmentType?: boolean
  seniority?: boolean
  salaryOrCompMentioned?: boolean
  requirements?: boolean
  requirementsNiceToHave?: boolean
  skillsMatched?: boolean
  skillsMissing?: boolean
  redFlags?: boolean
  nextStepForCandidate?: boolean
  action?: boolean
  isViewed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["application"]>

export type ApplicationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  postText?: boolean
  authorName?: boolean
  authorTitle?: boolean
  postUrl?: boolean
  datePosted?: boolean
  likesCount?: boolean
  source?: boolean
  externalUrls?: boolean
  linkedinJobUrls?: boolean
  linkedinProfileUrls?: boolean
  hashtagsInText?: boolean
  scrapedAt?: boolean
  activityUrn?: boolean
  postKind?: boolean
  jobRelevance?: boolean
  isFit?: boolean
  fitScore?: boolean
  fitReason?: boolean
  roleDetected?: boolean
  companyDetected?: boolean
  locationDetected?: boolean
  employmentType?: boolean
  seniority?: boolean
  salaryOrCompMentioned?: boolean
  requirements?: boolean
  requirementsNiceToHave?: boolean
  skillsMatched?: boolean
  skillsMissing?: boolean
  redFlags?: boolean
  nextStepForCandidate?: boolean
  action?: boolean
  isViewed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["application"]>

export type ApplicationSelectScalar = {
  id?: boolean
  postText?: boolean
  authorName?: boolean
  authorTitle?: boolean
  postUrl?: boolean
  datePosted?: boolean
  likesCount?: boolean
  source?: boolean
  externalUrls?: boolean
  linkedinJobUrls?: boolean
  linkedinProfileUrls?: boolean
  hashtagsInText?: boolean
  scrapedAt?: boolean
  activityUrn?: boolean
  postKind?: boolean
  jobRelevance?: boolean
  isFit?: boolean
  fitScore?: boolean
  fitReason?: boolean
  roleDetected?: boolean
  companyDetected?: boolean
  locationDetected?: boolean
  employmentType?: boolean
  seniority?: boolean
  salaryOrCompMentioned?: boolean
  requirements?: boolean
  requirementsNiceToHave?: boolean
  skillsMatched?: boolean
  skillsMissing?: boolean
  redFlags?: boolean
  nextStepForCandidate?: boolean
  action?: boolean
  isViewed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ApplicationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "postText" | "authorName" | "authorTitle" | "postUrl" | "datePosted" | "likesCount" | "source" | "externalUrls" | "linkedinJobUrls" | "linkedinProfileUrls" | "hashtagsInText" | "scrapedAt" | "activityUrn" | "postKind" | "jobRelevance" | "isFit" | "fitScore" | "fitReason" | "roleDetected" | "companyDetected" | "locationDetected" | "employmentType" | "seniority" | "salaryOrCompMentioned" | "requirements" | "requirementsNiceToHave" | "skillsMatched" | "skillsMissing" | "redFlags" | "nextStepForCandidate" | "action" | "isViewed" | "createdAt" | "updatedAt", ExtArgs["result"]["application"]>

export type $ApplicationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Application"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    postText: string
    authorName: string | null
    authorTitle: string | null
    postUrl: string | null
    datePosted: Date | null
    likesCount: number
    source: string | null
    externalUrls: string | null
    linkedinJobUrls: string | null
    linkedinProfileUrls: string | null
    hashtagsInText: string | null
    scrapedAt: Date
    activityUrn: string | null
    postKind: string | null
    jobRelevance: number | null
    isFit: boolean
    fitScore: number | null
    fitReason: string | null
    roleDetected: string | null
    companyDetected: string | null
    locationDetected: string | null
    employmentType: string | null
    seniority: string | null
    salaryOrCompMentioned: string | null
    requirements: string | null
    requirementsNiceToHave: string | null
    skillsMatched: string | null
    skillsMissing: string | null
    redFlags: string | null
    nextStepForCandidate: string | null
    action: string | null
    isViewed: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["application"]>
  composites: {}
}

export type ApplicationGetPayload<S extends boolean | null | undefined | ApplicationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApplicationPayload, S>

export type ApplicationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApplicationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApplicationCountAggregateInputType | true
  }

export interface ApplicationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Application'], meta: { name: 'Application' } }
  /**
   * Find zero or one Application that matches the filter.
   * @param {ApplicationFindUniqueArgs} args - Arguments to find a Application
   * @example
   * // Get one Application
   * const application = await prisma.application.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApplicationFindUniqueArgs>(args: Prisma.SelectSubset<T, ApplicationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Application that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApplicationFindUniqueOrThrowArgs} args - Arguments to find a Application
   * @example
   * // Get one Application
   * const application = await prisma.application.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApplicationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApplicationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Application that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFindFirstArgs} args - Arguments to find a Application
   * @example
   * // Get one Application
   * const application = await prisma.application.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApplicationFindFirstArgs>(args?: Prisma.SelectSubset<T, ApplicationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Application that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFindFirstOrThrowArgs} args - Arguments to find a Application
   * @example
   * // Get one Application
   * const application = await prisma.application.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApplicationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApplicationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Applications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Applications
   * const applications = await prisma.application.findMany()
   * 
   * // Get first 10 Applications
   * const applications = await prisma.application.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const applicationWithIdOnly = await prisma.application.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApplicationFindManyArgs>(args?: Prisma.SelectSubset<T, ApplicationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Application.
   * @param {ApplicationCreateArgs} args - Arguments to create a Application.
   * @example
   * // Create one Application
   * const Application = await prisma.application.create({
   *   data: {
   *     // ... data to create a Application
   *   }
   * })
   * 
   */
  create<T extends ApplicationCreateArgs>(args: Prisma.SelectSubset<T, ApplicationCreateArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Applications.
   * @param {ApplicationCreateManyArgs} args - Arguments to create many Applications.
   * @example
   * // Create many Applications
   * const application = await prisma.application.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApplicationCreateManyArgs>(args?: Prisma.SelectSubset<T, ApplicationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Applications and returns the data saved in the database.
   * @param {ApplicationCreateManyAndReturnArgs} args - Arguments to create many Applications.
   * @example
   * // Create many Applications
   * const application = await prisma.application.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Applications and only return the `id`
   * const applicationWithIdOnly = await prisma.application.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApplicationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApplicationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Application.
   * @param {ApplicationDeleteArgs} args - Arguments to delete one Application.
   * @example
   * // Delete one Application
   * const Application = await prisma.application.delete({
   *   where: {
   *     // ... filter to delete one Application
   *   }
   * })
   * 
   */
  delete<T extends ApplicationDeleteArgs>(args: Prisma.SelectSubset<T, ApplicationDeleteArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Application.
   * @param {ApplicationUpdateArgs} args - Arguments to update one Application.
   * @example
   * // Update one Application
   * const application = await prisma.application.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApplicationUpdateArgs>(args: Prisma.SelectSubset<T, ApplicationUpdateArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Applications.
   * @param {ApplicationDeleteManyArgs} args - Arguments to filter Applications to delete.
   * @example
   * // Delete a few Applications
   * const { count } = await prisma.application.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApplicationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApplicationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Applications
   * const application = await prisma.application.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApplicationUpdateManyArgs>(args: Prisma.SelectSubset<T, ApplicationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Applications and returns the data updated in the database.
   * @param {ApplicationUpdateManyAndReturnArgs} args - Arguments to update many Applications.
   * @example
   * // Update many Applications
   * const application = await prisma.application.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Applications and only return the `id`
   * const applicationWithIdOnly = await prisma.application.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApplicationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApplicationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Application.
   * @param {ApplicationUpsertArgs} args - Arguments to update or create a Application.
   * @example
   * // Update or create a Application
   * const application = await prisma.application.upsert({
   *   create: {
   *     // ... data to create a Application
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Application we want to update
   *   }
   * })
   */
  upsert<T extends ApplicationUpsertArgs>(args: Prisma.SelectSubset<T, ApplicationUpsertArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationCountArgs} args - Arguments to filter Applications to count.
   * @example
   * // Count the number of Applications
   * const count = await prisma.application.count({
   *   where: {
   *     // ... the filter for the Applications we want to count
   *   }
   * })
  **/
  count<T extends ApplicationCountArgs>(
    args?: Prisma.Subset<T, ApplicationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApplicationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Application.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApplicationAggregateArgs>(args: Prisma.Subset<T, ApplicationAggregateArgs>): Prisma.PrismaPromise<GetApplicationAggregateType<T>>

  /**
   * Group by Application.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApplicationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApplicationGroupByArgs['orderBy'] }
      : { orderBy?: ApplicationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApplicationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApplicationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Application model
 */
readonly fields: ApplicationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Application.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApplicationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Application model
 */
export interface ApplicationFieldRefs {
  readonly id: Prisma.FieldRef<"Application", 'String'>
  readonly postText: Prisma.FieldRef<"Application", 'String'>
  readonly authorName: Prisma.FieldRef<"Application", 'String'>
  readonly authorTitle: Prisma.FieldRef<"Application", 'String'>
  readonly postUrl: Prisma.FieldRef<"Application", 'String'>
  readonly datePosted: Prisma.FieldRef<"Application", 'DateTime'>
  readonly likesCount: Prisma.FieldRef<"Application", 'Int'>
  readonly source: Prisma.FieldRef<"Application", 'String'>
  readonly externalUrls: Prisma.FieldRef<"Application", 'String'>
  readonly linkedinJobUrls: Prisma.FieldRef<"Application", 'String'>
  readonly linkedinProfileUrls: Prisma.FieldRef<"Application", 'String'>
  readonly hashtagsInText: Prisma.FieldRef<"Application", 'String'>
  readonly scrapedAt: Prisma.FieldRef<"Application", 'DateTime'>
  readonly activityUrn: Prisma.FieldRef<"Application", 'String'>
  readonly postKind: Prisma.FieldRef<"Application", 'String'>
  readonly jobRelevance: Prisma.FieldRef<"Application", 'Int'>
  readonly isFit: Prisma.FieldRef<"Application", 'Boolean'>
  readonly fitScore: Prisma.FieldRef<"Application", 'Int'>
  readonly fitReason: Prisma.FieldRef<"Application", 'String'>
  readonly roleDetected: Prisma.FieldRef<"Application", 'String'>
  readonly companyDetected: Prisma.FieldRef<"Application", 'String'>
  readonly locationDetected: Prisma.FieldRef<"Application", 'String'>
  readonly employmentType: Prisma.FieldRef<"Application", 'String'>
  readonly seniority: Prisma.FieldRef<"Application", 'String'>
  readonly salaryOrCompMentioned: Prisma.FieldRef<"Application", 'String'>
  readonly requirements: Prisma.FieldRef<"Application", 'String'>
  readonly requirementsNiceToHave: Prisma.FieldRef<"Application", 'String'>
  readonly skillsMatched: Prisma.FieldRef<"Application", 'String'>
  readonly skillsMissing: Prisma.FieldRef<"Application", 'String'>
  readonly redFlags: Prisma.FieldRef<"Application", 'String'>
  readonly nextStepForCandidate: Prisma.FieldRef<"Application", 'String'>
  readonly action: Prisma.FieldRef<"Application", 'String'>
  readonly isViewed: Prisma.FieldRef<"Application", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Application", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Application", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Application findUnique
 */
export type ApplicationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Filter, which Application to fetch.
   */
  where: Prisma.ApplicationWhereUniqueInput
}

/**
 * Application findUniqueOrThrow
 */
export type ApplicationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Filter, which Application to fetch.
   */
  where: Prisma.ApplicationWhereUniqueInput
}

/**
 * Application findFirst
 */
export type ApplicationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Filter, which Application to fetch.
   */
  where?: Prisma.ApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Applications to fetch.
   */
  orderBy?: Prisma.ApplicationOrderByWithRelationInput | Prisma.ApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Applications.
   */
  cursor?: Prisma.ApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Applications.
   */
  distinct?: Prisma.ApplicationScalarFieldEnum | Prisma.ApplicationScalarFieldEnum[]
}

/**
 * Application findFirstOrThrow
 */
export type ApplicationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Filter, which Application to fetch.
   */
  where?: Prisma.ApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Applications to fetch.
   */
  orderBy?: Prisma.ApplicationOrderByWithRelationInput | Prisma.ApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Applications.
   */
  cursor?: Prisma.ApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Applications.
   */
  distinct?: Prisma.ApplicationScalarFieldEnum | Prisma.ApplicationScalarFieldEnum[]
}

/**
 * Application findMany
 */
export type ApplicationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Filter, which Applications to fetch.
   */
  where?: Prisma.ApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Applications to fetch.
   */
  orderBy?: Prisma.ApplicationOrderByWithRelationInput | Prisma.ApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Applications.
   */
  cursor?: Prisma.ApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Applications.
   */
  distinct?: Prisma.ApplicationScalarFieldEnum | Prisma.ApplicationScalarFieldEnum[]
}

/**
 * Application create
 */
export type ApplicationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * The data needed to create a Application.
   */
  data: Prisma.XOR<Prisma.ApplicationCreateInput, Prisma.ApplicationUncheckedCreateInput>
}

/**
 * Application createMany
 */
export type ApplicationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Applications.
   */
  data: Prisma.ApplicationCreateManyInput | Prisma.ApplicationCreateManyInput[]
}

/**
 * Application createManyAndReturn
 */
export type ApplicationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * The data used to create many Applications.
   */
  data: Prisma.ApplicationCreateManyInput | Prisma.ApplicationCreateManyInput[]
}

/**
 * Application update
 */
export type ApplicationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * The data needed to update a Application.
   */
  data: Prisma.XOR<Prisma.ApplicationUpdateInput, Prisma.ApplicationUncheckedUpdateInput>
  /**
   * Choose, which Application to update.
   */
  where: Prisma.ApplicationWhereUniqueInput
}

/**
 * Application updateMany
 */
export type ApplicationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Applications.
   */
  data: Prisma.XOR<Prisma.ApplicationUpdateManyMutationInput, Prisma.ApplicationUncheckedUpdateManyInput>
  /**
   * Filter which Applications to update
   */
  where?: Prisma.ApplicationWhereInput
  /**
   * Limit how many Applications to update.
   */
  limit?: number
}

/**
 * Application updateManyAndReturn
 */
export type ApplicationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * The data used to update Applications.
   */
  data: Prisma.XOR<Prisma.ApplicationUpdateManyMutationInput, Prisma.ApplicationUncheckedUpdateManyInput>
  /**
   * Filter which Applications to update
   */
  where?: Prisma.ApplicationWhereInput
  /**
   * Limit how many Applications to update.
   */
  limit?: number
}

/**
 * Application upsert
 */
export type ApplicationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * The filter to search for the Application to update in case it exists.
   */
  where: Prisma.ApplicationWhereUniqueInput
  /**
   * In case the Application found by the `where` argument doesn't exist, create a new Application with this data.
   */
  create: Prisma.XOR<Prisma.ApplicationCreateInput, Prisma.ApplicationUncheckedCreateInput>
  /**
   * In case the Application was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApplicationUpdateInput, Prisma.ApplicationUncheckedUpdateInput>
}

/**
 * Application delete
 */
export type ApplicationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Filter which Application to delete.
   */
  where: Prisma.ApplicationWhereUniqueInput
}

/**
 * Application deleteMany
 */
export type ApplicationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Applications to delete
   */
  where?: Prisma.ApplicationWhereInput
  /**
   * Limit how many Applications to delete.
   */
  limit?: number
}

/**
 * Application without action
 */
export type ApplicationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
}
